packages:
  - core
  - service
  - test
  - web

allowBuilds:
  '@google/genai': false
  '@nkzw/mdx-editor': true
  '@swc/core': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  native-keymap: true
  node-pty: true
  protobufjs: false
  sharp: true
  workerd: true
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - '@nkzw/*'
  - void-fate@1.7.0
  - '@void/deploy-cloudflare@0.21.2'
  - '@void/deploy-core@0.21.2'
  - '@void/edge@0.21.2'
  - '@void/isr@0.21.2'
  - '@void/platform@0.21.2'
  - '@void/react@0.21.2'
  - react-fate@1.7.0
  - void@0.21.2
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  vitest: 5.0.2
nodeLinker: hoisted
onlyBuiltDependencies:
  - '@nkzw/mdx-editor'
  - '@swc/core'
  - electron
  - electron-winstaller
  - unrs-resolver
overrides:
  extract-zip>yauzl: ^3.4.0
  vite@*: 'catalog:'
patchedDependencies:
  native-keymap@3.3.9: patches/native-keymap@3.3.9.patch
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
